### ISSUE TITLE
Where can I find the installation instructions?

### ISSUE THREAD

**Issue by JaimyPolhuis** [thecrmninja/Power-Platform-Capacity-Monitoring#1]
Hi, 

Interesting dashboard you have here. I was looking for installation instructions as I am not very familiar with how to do these kind of things. Are these available?

Looking forward to a reply.

Kind regards,
Jaimy

**Comment by thecrmninja** [comment]
Hi Jaimy

You'll need to download the solution & import it into a Power Platform environment. If you're new to this, I'd recommend taking a look at https://learn.microsoft.com/en-us/power-apps/maker/data-platform/import-update-export-solutions
